In [1]:
import numpy as np
import healpy as hp
import shtns
import math
import pylab as plt
import zm_tools as zt
import kjones
import polarization_field_transform as pft

In [2]:
jones_data = kjones.get_hera_jones()

In [26]:
jones = jones_data['jones']
theta_j = jones_data['theta']
phi_j = jones_data['phi']

In [27]:
lmax = 178
mmax = lmax
sh = shtns.sht(lmax,mmax=mmax)

In [6]:
shtns.sht?

In [28]:
nlat = 180
nphi = 360
grid_type = shtns.sht_reg_fast
polar_opt_threshold = 1.0e-10

In [29]:
sh.set_grid(nlat,nphi,flags=grid_type,polar_opt=polar_opt_threshold)

[180, 360]

In [30]:
el = sh.l
xx_beam = sh.spat_array()
xx_beam_ylm = sh.spec_array()

In [36]:
dx_data = np.reshape(jones[0,0,:]*np.conjugate(jones[0,0,:]) + jones[0,1,:]*np.conjugate(jones[0,1,:]),\
                     (181,360))

In [39]:
theta_m,phi_m = np.meshgrid(np.arange(180)*np.pi/179.,np.arange(360)*np.pi/359.)

In [50]:
print theta_m.shape
print phi_m.shape

(360, 180)
(360, 180)


In [43]:
theta_jm = theta_j.reshape(360,181)

In [51]:
theta_jm[0,:]

array([ 0.        ,  0.01745329,  0.03490659,  0.05235988,  0.06981317,
        0.08726646,  0.10471976,  0.12217305,  0.13962634,  0.15707963,
        0.17453293,  0.19198622,  0.20943951,  0.2268928 ,  0.2443461 ,
        0.26179939,  0.27925268,  0.29670597,  0.31415927,  0.33161256,
        0.34906585,  0.36651914,  0.38397244,  0.40142573,  0.41887902,
        0.43633231,  0.45378561,  0.4712389 ,  0.48869219,  0.50614548,
        0.52359878,  0.54105207,  0.55850536,  0.57595865,  0.59341195,
        0.61086524,  0.62831853,  0.64577182,  0.66322512,  0.68067841,
        0.6981317 ,  0.71558499,  0.73303829,  0.75049158,  0.76794487,
        0.78539816,  0.80285146,  0.82030475,  0.83775804,  0.85521133,
        0.87266463,  0.89011792,  0.90757121,  0.9250245 ,  0.9424778 ,
        0.95993109,  0.97738438,  0.99483767,  1.01229097,  1.02974426,
        1.04719755,  1.06465084,  1.08210414,  1.09955743,  1.11701072,
        1.13446401,  1.15191731,  1.1693706 ,  1.18682389,  1.20

In [52]:
theta_m[0,:]

array([ 0.        ,  0.0175508 ,  0.03510159,  0.05265239,  0.07020319,
        0.08775398,  0.10530478,  0.12285558,  0.14040638,  0.15795717,
        0.17550797,  0.19305877,  0.21060956,  0.22816036,  0.24571116,
        0.26326195,  0.28081275,  0.29836355,  0.31591435,  0.33346514,
        0.35101594,  0.36856674,  0.38611753,  0.40366833,  0.42121913,
        0.43876992,  0.45632072,  0.47387152,  0.49142231,  0.50897311,
        0.52652391,  0.54407471,  0.5616255 ,  0.5791763 ,  0.5967271 ,
        0.61427789,  0.63182869,  0.64937949,  0.66693028,  0.68448108,
        0.70203188,  0.71958267,  0.73713347,  0.75468427,  0.77223507,
        0.78978586,  0.80733666,  0.82488746,  0.84243825,  0.85998905,
        0.87753985,  0.89509064,  0.91264144,  0.93019224,  0.94774304,
        0.96529383,  0.98284463,  1.00039543,  1.01794622,  1.03549702,
        1.05304782,  1.07059861,  1.08814941,  1.10570021,  1.123251  ,
        1.1408018 ,  1.1583526 ,  1.1759034 ,  1.19345419,  1.21

In [31]:
theta_v_f = theta_v.flatten()
phi_v_f = phi_v.transpose().flatten()

In [25]:
theta_j0 = np.asarray(np.where(theta_j==0)).squeeze()

In [72]:
theta_js = np.delete(theta_j,theta_j0)
phi_js = np.delete(phi_j,theta_j0)
j_txs = np.delete(j_tx,theta_j0)

In [74]:
j_txs.shape

(64800,)

In [78]:
theta_jsv = np.reshape(theta_js,(180,360))
phi_jsv = np.reshape(theta_js,(180,360))

In [84]:
phi_jsv[:,1]

array([ 0.03490659,  0.03490659,  0.03490659,  0.03490659,  0.03490659,
        0.03490659,  0.03490659,  0.03490659,  0.03490659,  0.03490659,
        0.03490659,  0.03490659,  0.03490659,  0.03490659,  0.03490659,
        0.03490659,  0.03490659,  0.03490659,  0.03490659,  0.03490659,
        0.03490659,  0.03490659,  0.03490659,  0.03490659,  0.03490659,
        0.03490659,  0.03490659,  0.03490659,  0.03490659,  0.03490659,
        0.03490659,  0.03490659,  0.03490659,  0.03490659,  0.03490659,
        0.03490659,  0.03490659,  0.03490659,  0.03490659,  0.03490659,
        0.03490659,  0.03490659,  0.03490659,  0.03490659,  0.03490659,
        0.03490659,  0.03490659,  0.03490659,  0.03490659,  0.03490659,
        0.03490659,  0.03490659,  0.03490659,  0.03490659,  0.03490659,
        0.03490659,  0.03490659,  0.03490659,  0.03490659,  0.03490659,
        0.03490659,  0.03490659,  0.03490659,  0.03490659,  0.03490659,
        0.03490659,  0.03490659,  0.03490659,  0.03490659,  0.03

In [85]:
phi_js[360:540]

array([ 0.03490659,  0.03490659,  0.03490659,  0.03490659,  0.03490659,
        0.03490659,  0.03490659,  0.03490659,  0.03490659,  0.03490659,
        0.03490659,  0.03490659,  0.03490659,  0.03490659,  0.03490659,
        0.03490659,  0.03490659,  0.03490659,  0.03490659,  0.03490659,
        0.03490659,  0.03490659,  0.03490659,  0.03490659,  0.03490659,
        0.03490659,  0.03490659,  0.03490659,  0.03490659,  0.03490659,
        0.03490659,  0.03490659,  0.03490659,  0.03490659,  0.03490659,
        0.03490659,  0.03490659,  0.03490659,  0.03490659,  0.03490659,
        0.03490659,  0.03490659,  0.03490659,  0.03490659,  0.03490659,
        0.03490659,  0.03490659,  0.03490659,  0.03490659,  0.03490659,
        0.03490659,  0.03490659,  0.03490659,  0.03490659,  0.03490659,
        0.03490659,  0.03490659,  0.03490659,  0.03490659,  0.03490659,
        0.03490659,  0.03490659,  0.03490659,  0.03490659,  0.03490659,
        0.03490659,  0.03490659,  0.03490659,  0.03490659,  0.03